### ISSUE TITLE
Styling issues - spacing and text positioning

### ISSUE THREAD

**Issue by jschof1** [adaptlearning/adapt-contrib-accordion#110]
Expectation:
![image](https://user-images.githubusercontent.com/59843981/148767448-a4752984-61dd-41d8-ba4d-5d805a08f5a9.png)

How it looks once updated:
![image](https://user-images.githubusercontent.com/59843981/148767505-9beafa18-328f-4c1e-bd73-b8ae1bef5629.png)

**Comment by oliverfoster** [comment]
It looks as though updates to the class names happened in the last pr https://github.com/adaptlearning/adapt-contrib-accordion/pull/109/files
You'll need to update your theme.

**Comment by jschof1** [comment]
Got it thanks
