### ISSUE TITLE
Item headers not auto-generating appropriate heading level

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-accordion#120]
## Bug Description:
The aria heading level for each accordion item is being assigned a value of '5'.

## Steps to Reproduce:
Using a screenreader, navigate through the elements of an accordion component
Note the heading level of each accordion item

## Actual Behavior:
`<div role="heading" aria-level="5"></div>`

## Expected Behavior:
I'm able to change the heading level of each accordion item if I assign an `_ariaLevel` at the component heading level. But this should specifically be following the heading level rules set up previously in the following ticket: https://github.com/adaptlearning/adapt-contrib-core/pull/146

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/180727419-0ae36b1f-24b8-4e94-91ca-3566a3fd0c41.png)

It's working fine for me @joe-replin 
Are you sure the config.json:_ariaLevels are setup correctly?

**Comment by oliverfoster** [comment]
works for me
