### ISSUE TITLE
Normalize icons globally

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-accordion#135]
### Subject of the issue/enhancement/features
Not a bug, but more housecleaning. Looking to ensure all icons in every template are uniform and set up with the same structure with the appropriate aria hidden label.
```
<span className="component-item__icon" aria-hidden="true">
  <span className="icon"></span>
</span>
```
OR
```
<span className="component-item__icon" aria-label="ARIA Description.">
  <span className="icon" aria-hidden="true"></span>
</span>
```

**Comment by oliverfoster** [comment]
@guywillis svg icons time?

**Comment by oliverfoster** [comment]
@joe-replin can you make sure tha the thing actual icon had aria-hidden instead of the parent please?
the aira-hidden is to stop the `css { content:'thistext' }` from reading.

**Comment by joe-replin** [comment]
After further review and discussion, this plug-in was already in a good state. Closing PR, Branch & Ticket!
