### ISSUE TITLE
Tick icon issue

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-accordion#140]
### Subject of the issue
I suggest that the `-` icon is unnecessary, this is as it indicates that the button _can_ be collapsed but occludes the completion tick. I would suggest that we go from `+` to `tick` without the `-` as it imparts no useful information. It is not necessary to collapse to complete the item.
Hotgraphic only has `+` and `tick`.

All incomplete:
![image](https://github.com/adaptlearning/adapt-contrib-accordion/assets/7974663/dc262694-e7ad-42ce-b919-53ffe2c22ead)

1 item complete but expanded, item does not look complete:
![image](https://github.com/adaptlearning/adapt-contrib-accordion/assets/7974663/32c0c3d2-ab98-4288-80e8-16c21f5820bd)

2 items complete, all collapsed:
![image](https://github.com/adaptlearning/adapt-contrib-accordion/assets/7974663/380e438d-26af-497b-ad56-1e1d63753e59)

all items complete, one expanded:
![image](https://github.com/adaptlearning/adapt-contrib-accordion/assets/7974663/9b072e15-1625-4481-ae48-0f7deeb05691)

**Comment by guywillis** [comment]
I agree with `-` being unnecessary. 

Perhaps though, replacing `+` and `-` with a downwards facing chevron would be more intuitive if we followed the rules of:

* `+` opens an overlay
* downwards chevron reveals content (either through accordion or trickle)

Keen to hear your thoughts @oliverfoster

**Comment by guywillis** [comment]
> I have previously found icons with directionality a little irritating with RTL.

Is that true with vertical orientated icons?

**Comment by oliverfoster** [comment]
> Do you find that to play true even with vertical orientated icons?

Of course not. I was just pondering it in case there was something similar with up/downs.

You're right, the standard icons for collapse/expand seem to be either:
* -/+ 
* ^/⌄ 
* -/⌄

I think we use:

* Up/Down for scrolling (scroll to top, trickle, tc)
* Left/Right horizontal items (narrative, hotgraphic, etc)

Is it sensible to use Down for revealing content as well? 

I guess it depends if you want to distinguish between a narrative/hotgraphic-popup reveal (left/right), a hotgraphic-pin-notify/accordion reveal (+), a drawer reveal (various icons) and menu navigate (View). Or if we just use a + for any kind of nested component item reveal (accordion, hotgraphic -pin, etc)? Or if we use Down for any kind of downward reveal, scroll or otherwise? I don't really know, it depends what makes most sense. Down for trickle seems to me very much not the same down for accordion, but I'm happy to give way to it if it feels right in practise as the default?

There is definitely an accessibility distinction between a menu View button (navigation) and a Drawer (expand/collapse + modal dialog) or Notify (modal dialog) or Accordion (expand/collapse) button or Tabs (selected/unselected)

**Comment by guywillis** [comment]
Agreed that the downward directional chevron is outside the scope of the issue.

Happy to proceed with replacing the `-` on an accordion item when it is opened with a tick to signify completion.
