### ISSUE TITLE
iPad on Moodle shoots to top of page

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt-contrib-accordion#70]
When opening an accordion section on iPad2 (ios9.1) in Moodle 2.7 in a new window, you are shot back to the top of the page and have to scroll back down to see the open accordion.

**Comment by hmaffin** [comment]
Also on iPad 4 (ios7) after clicking a section you get a white page overlay

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#845
